version: "3.5"
# Você terá 1.5 CPUs e 3.0GB 
services:
 db:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER:  rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    command: 'postgres -c max_connections=210 -c shared_buffers=256MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'  
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '0.9GB'
 
 api1:
    image: davidlins/rinha-backend-servlet
    container_name: api1
    hostname:  api1
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    depends_on:
        - db
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.9GB'

 api2:
    image: davidlins/rinha-backend-servlet
    container_name: api2
    hostname:  api2
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    depends_on:
        - dp
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.9GB'

 nginx:
    image: nginx 
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
        - api1
        - api2
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'
